### ISSUE TITLE
Invalid Bundle Structure - The binary file 'XXXX.app/modules/ti.speechkit/SpeechKit.framework/SpeechKit' is not permitted

### ISSUE THREAD

**Issue by gvlamadrid** [benbahrenburg/Ti.SpeechKit#6]
When upload app with Application Loadter

ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'XXXX.app/modules/ti.speechkit/SpeechKit.framework/SpeechKit' is not permitted. Your app can’t contain standalone executables or libraries, other than the CFBundleExecutable of supported bundles. 

Any idea? txs

**Comment by benbahrenburg** [comment]
Sounds like this might address the error you are receiving :
http://onebigfunction.com/ios/2015/03/15/invalid-bundle-structure/

**Comment by gvlamadrid** [comment]
txs! I thought that but is empty "Copy Bundle Resources".

**Comment by benbahrenburg** [comment]
you have a list on how to resolve?

**Comment by gvlamadrid** [comment]
I couldnt resolve yet

**Comment by gvlamadrid** [comment]
I found the solution moving the framework to platform.

**Comment by amit-pandey11** [comment]
Hey @gvlamadrid 
Can you explain how you had resolved this issue? I am facing the same issue with PayTM integration and I am not able to get the solution. 
Thanks
